name: pert6
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  intl: ^0.18.1
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  page_transition: ^2.1.0
  geolocator: ^10.1.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  geocoding: ^2.1.1
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/weather/
